//frontend\src\styles\screens\voluntario\DashboardStyles.ts

import { StyleSheet } from "react-native";
import { Colors } from "../../colors";
import { typography } from "../../typography";

const styles = StyleSheet.create({
  container: {
    padding: 18,
    paddingBottom: 30,
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: 35,
  },
  title: {
    fontFamily: "Inter_600SemiBold",
    marginTop: 5,
    textAlign: "center",
    fontSize: 24,
    color: Colors.primary,
  },
  subtitle: {
    fontFamily: "Inter_400Regular",
    marginTop: 5,
    color: Colors.text,
    textAlign: "center",
    fontSize: 15,
    marginBottom: 30,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 25,
    flex: 1,
    marginVertical: 10,
    marginBottom: 30,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    elevation: 3,
    borderWidth: 0.05,
    borderColor: Colors.lightGray,
  },

  name: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 18,
    marginTop: 8,
    marginLeft: 1.5,
    textAlign: "center",
    alignContent: "center",
    color: Colors.text,
  },
  estadoVoluntario: {
    alignItems: "center",
    backgroundColor: Colors.tertiary,
    borderRadius: 8,
    elevation: 2,
    marginTop: 15,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderColor: Colors.lightGray,
    borderWidth: 1,
  },
  estado: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: Colors.text,
    textAlign: "center",
  },
  avisoCard: {
    backgroundColor: Colors.tertiary,
    borderRadius: 8,
    elevation: 2,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  avisoText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    marginTop: 3,
    color: Colors.text,
    padding: 5,
    textAlign: "center",
  },
  subtituloAviso: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: Colors.text,
    textAlign: "center",
    padding: 5,
    marginTop: -5,
  },
  buttonQR: {
    borderWidth: 1,
    borderColor: Colors.primary,
    paddingVertical: 10,
    borderRadius: 8,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primary,
    width: "100%",
    elevation: 3,
  },
  button: {
    borderWidth: 1,
    borderColor: Colors.primary,
    paddingVertical: 10,
    borderRadius: 8,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    width: "100%",
    elevation: 3,
  },
  buttonTextQR: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: Colors.white,
    shadowOpacity: 0.05,
    marginLeft: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
  },
  buttonText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
    color: Colors.text,
    shadowOpacity: 0.05,
    shadowColor: "#000",
    marginLeft: 10,
    shadowOffset: { width: 0, height: 2 },
  },
  editButton: {
    backgroundColor: Colors.lightGreen, // fondo semi-transparente
    marginLeft: 5,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  label: {
    fontSize: 16,
    color: "#333",
    marginBottom: 8,
    marginTop: 20,
    fontWeight: "500",
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
  },
});

export default styles;
