//frontend\src\styles\screens\voluntario\EditProfileStyles.ts

import { StyleSheet } from "react-native";
import { Colors } from "../../colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 35,
    backgroundColor: Colors.background,
  },
  mainCard: {
    width: "100%",
    backgroundColor: Colors.white,
    paddingVertical: 25,
    paddingHorizontal: 20,
    borderRadius: 18,
    borderWidth: 0.5,
    borderColor: Colors.lightGray,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 3,
    marginTop: 10,
  },
  data: {
    fontSize: 16,
    color: Colors.text,
    marginBottom: 20,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.3,
  },
  divisorline: {
    height: 1,
    backgroundColor: Colors.text,
    marginVertical: 15,
    alignSelf: "center",
    width: "100%",
    marginBottom: 30,
  },
  label: {
    fontSize: 15,
    color: Colors.text,
    marginBottom: 6,
    fontFamily: "Inter_500Medium",
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.lightGray,
    backgroundColor: "#F9FAFB",
    color: Colors.text,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    marginBottom: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  readOnlyContainer: {
    marginBottom: 20,
  },
  readOnlyLabel: {
    fontSize: 13,
    color: Colors.gray,
    fontFamily: "Inter_400Regular",
    marginBottom: 4,
  },
  readOnlyValue: {
    fontSize: 15,
    color: Colors.text,
    fontFamily: "Inter_500Medium",
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.lightGray,
  },
  saveButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 28,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  saveButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.5,
  },
  changePasswordButton: {
    marginTop: 18,
    backgroundColor: Colors.white,
    borderWidth: 1.3,
    borderColor: Colors.primary,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 40,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  changePasswordButtonText: {
    color: Colors.primary,
    fontSize: 15.5,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.4,
  },
  disabledButton: {
    opacity: 0.6,
  },
});
