//frontend\src\styles\screens\guardia\DashboardGuardiaStyles.ts

import { StyleSheet } from "react-native";
import { Colors } from "../../colors";
import { typography } from "../../typography";

export const styles = StyleSheet.create({
  scrollContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  container: {
    padding: 18,
    paddingBottom: 30,
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: 25,
  },
  containerView: {
    padding: 18,
    flex: 1,
  },
  divisorline: {
    height: 1,
    backgroundColor: Colors.text,
    marginVertical: 15,
    alignSelf: "center",
    width: "100%",
    marginBottom: -15,
  },
  card: {
    width: "100%",
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    borderWidth: 0.5,
    borderColor: Colors.gray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    alignItems: "center",
    elevation: 2,
  },
  iconCircle: {
    width: 59.17,
    height: 59.17,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: Colors.brown,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  title: {
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    color: Colors.text,
    marginTop: 5,
  },
  subtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    marginTop: 5,
    color: Colors.text,
    marginBottom: 20,
  },
  scannerBox: {
    width: 290,
    height: 290,
    borderRadius: 21,
    backgroundColor: "#040404",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 18,
  },
  scanButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: Colors.gray,
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    marginBottom: 20,
    marginTop: 10,
    elevation: 3,
  },
  scanButtonText: {
    color: Colors.white,
    fontFamily: "Inter_500Medium",
    fontSize: 14,
  },
  instructionsBox: {
    backgroundColor: "#F8F6F6",
    padding: 12,
    borderRadius: 8,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 5,
    marginTop: 10,
    elevation: 3,
  },
  instructionsTitle: {
    fontFamily: "Inter_500Medium",
    fontSize: 12,
    marginBottom: 3,
    color: Colors.text,
  },
  instructionsText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.text,
    marginBottom: 3,
  },
  buttonContainer: {
    width: "90%",
    alignItems: "center",
  },
  resultText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    textAlign: "center",
  },
  resultBox: {
    width: 290,
    height: 290,
    borderRadius: 21,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 15,
    elevation: 2,
  },
  resultSubText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.text,
    marginTop: 5,
    textAlign: "center",
  },
  QRBox: {
    width: 250,
    height: 250,
    borderRadius: 25,
    backgroundColor: "#333140",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
});
