//frontend\src\styles\screens\auth\ForgotPasswordStyles.ts
import { StyleSheet } from "react-native";
import { Colors } from "../../colors";
import { typography } from "../../typography";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 25,
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: 25,
    resizeMode: "contain",
  },
  backContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
    paddingTop: 25,
    flexWrap: "wrap",
    position: "absolute",
    top: 42,
    left: 36,
  },
  title: {
    fontFamily: "Inter_700Bold",
    fontSize: 24,
    textAlign: "center",
    paddingLeft: 8,
    color: Colors.text,
  },
  subtitle: {
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    color: Colors.text,
    marginTop: 15,
    textAlign: "center",
    paddingLeft: 8,
    flexWrap: "wrap",
    marginBottom: 30,
  },
  label: {
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
    fontSize: 14,
    marginTop: 15,
    marginBottom: 10,
    alignSelf: "flex-start",
    paddingLeft: 28,
    flexWrap: "wrap",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 15,
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    backgroundColor: Colors.white,
    alignContent: "center",
    width: "85%",
  },
  registerButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: Colors.gray,
    alignItems: "center",
    justifyContent: "center",
    width: "85%",
    marginTop: 15,
    shadowColor: Colors.text,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  registerText: {
    color: Colors.white,
    fontFamily: "Inter_500Medium",
    fontSize: 14,
  },
  footer:{
    fontFamily: "Inter_500Medium",
    marginTop: 25,
    fontSize: 13,
    color: Colors.text,
  },
});
