//frontend/src/styles/screens/auth/RegisterStyles.ts

import { StyleSheet } from "react-native";
import { Colors } from "../../colors";
import { typography } from "../../typography";

export const styles = StyleSheet.create({
  scrollContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  container: {
    padding: 18,
    paddingBottom: 30,
  },
  backContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    paddingTop: 25,
    flexWrap: "wrap",
    alignContent: "center",
  },
  title: {
    fontFamily: "Inter_400Regular",
    fontSize: 20,
    textAlign: "left",
    paddingLeft: 8,
    color: Colors.green,
    flexWrap: "wrap",
  },
  label: {
    fontFamily: "Inter_500Medium",
    fontSize: 14,
    marginBottom: 5,
    color: Colors.text,
    marginTop: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 15,
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    backgroundColor: Colors.lightGray,
  },
  multilineInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 15,
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    backgroundColor: Colors.lightGray,
    minHeight: 50,
    maxHeight: 90,
  },
  uploadButton: {
    borderWidth: 1,
    borderColor: Colors.gray,
    borderRadius: 8,
    padding: 12,
    alignItems: "flex-start",
    marginTop: 5,
  },
  aviso: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
    flexWrap: "wrap",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: Colors.gray,
    borderRadius: 3,
    marginRight: 10,
    marginTop: 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  checkmark: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: "bold",
  },
  avisoText: {
    flex: 1,
    flexWrap: "wrap",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.text,
    lineHeight: 18,
  },
  avisoLink: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    color: Colors.green,
    textDecorationLine: "underline",
    lineHeight: 18,
    flexWrap: "wrap",
  },
  solicitudButton: {
    backgroundColor: Colors.primary,
    padding: 15,
    borderRadius: 8,
    marginTop: 20,
  },
  subtitle: {
    ...typography.body,
    color: Colors.green,
    marginBottom: 10,
    fontSize: 20,
    marginTop: 15,
  },
  form: {
    width: "100%",
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    borderWidth: 0.5,
    borderColor: Colors.gray,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    marginBottom: 30,
  },
  divisorline: {
    height: 1,
    backgroundColor: Colors.text,
    marginVertical: 15,
    alignSelf: "center",
    width: "100%",
    marginBottom: 30,
  },
  registerButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: Colors.gray,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    shadowColor: Colors.text,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  registerText: {
    color: Colors.white,
    fontFamily: "Inter_500Medium",
    fontSize: 14,
  },
  uploadButtonText: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
});
